@rem Step 1. Set Sample - Overshadow environments
set SAMPLE_OVERSHADOW_NAME=Overshadow
set SAMPLE_OVERSHADOW_SRC_ROOT=%ENLISTMENT_PROJ_ROOT%\src\Sample\%SAMPLE_OVERSHADOW_NAME%
set SAMPLE_OVERSHADOW_BIN_ROOT=%ENLISTMENT_PROJ_ROOT%\bin\Sample\%SAMPLE_OVERSHADOW_NAME%
set SAMPLE_OVERSHADOW_LOG_ROOT=%SAMPLE_OVERSHADOW_BIN_ROOT%\log

@rem Step 2. Set Sample - SNProtector environments
set SAMPLE_SNPROTECTOR_NAME=SNProtector
set SAMPLE_SNPROTECTOR_SRC_ROOT=%ENLISTMENT_PROJ_ROOT%\src\Sample\%SAMPLE_SNPROTECTOR_NAME%
set SAMPLE_SNPROTECTOR_BIN_ROOT=%ENLISTMENT_PROJ_ROOT%\bin\Sample\%SAMPLE_SNPROTECTOR_NAME%
set SAMPLE_SNPROTECTOR_LOG_ROOT=%SAMPLE_SNPROTECTOR_BIN_ROOT%\log

@rem Step 3. Set Sample - AntiDebugger environments
set SAMPLE_ANTIDEBUGGER_NAME=AntiDebugger
set SAMPLE_ANTIDEBUGGER_SRC_ROOT=%ENLISTMENT_PROJ_ROOT%\src\Sample\%SAMPLE_ANTIDEBUGGER_NAME%
set SAMPLE_ANTIDEBUGGER_BIN_ROOT=%ENLISTMENT_PROJ_ROOT%\bin\Sample\%SAMPLE_ANTIDEBUGGER_NAME%
set SAMPLE_ANTIDEBUGGER_LOG_ROOT=%SAMPLE_ANTIDEBUGGER_BIN_ROOT%\log


@rem Final. Create Important bin path
if not exist %SAMPLE_OVERSHADOW_BIN_ROOT% mkdir %SAMPLE_OVERSHADOW_BIN_ROOT%
if not exist %SAMPLE_OVERSHADOW_LOG_ROOT% mkdir %SAMPLE_OVERSHADOW_LOG_ROOT%
if not exist %SAMPLE_SNPROTECTOR_BIN_ROOT% mkdir %SAMPLE_SNPROTECTOR_BIN_ROOT%
if not exist %SAMPLE_SNPROTECTOR_LOG_ROOT% mkdir %SAMPLE_SNPROTECTOR_LOG_ROOT%
if not exist %SAMPLE_ANTIDEBUGGER_BIN_ROOT% mkdir %SAMPLE_ANTIDEBUGGER_BIN_ROOT%
if not exist %SAMPLE_ANTIDEBUGGER_LOG_ROOT% mkdir %SAMPLE_ANTIDEBUGGER_LOG_ROOT%

@rem Step 1. Set command alias 
doskey /OVERSTRIKE bos=%ENLISTMENT_PROJ_ROOT%\src\Sample\Overshadow\build_code.bat
doskey /OVERSTRIKE src=cd /d %SAMPLE_OVERSHADOW_SRC_ROOT%
doskey /OVERSTRIKE bin=cd /d 5SAMPLE_OVERSHADOW_BIN_ROOT%
doskey /OVERSTRIKE bp=%ENLISTMENT_PROJ_ROOT%\src\Sample\SNProtector\build_code.bat